;; Time-stamp: <root 01/22/2013 15:46:37>

;; insert-copyright
(defun my-insert-copyright ()
  "Insert date at point."
  (interactive)
 (let ((cut "//============================================================================")
   (Name "// Name           : ")
   (LastChangeTime "// LastChangeTime : Time-stamp: <>")
   (Version "// Version        : 1.0")
   (Copyright "// Copyright      : 裸奔的鸡蛋")
   (Description "// Description    : ")
   (CreatDate "// CreatDate      : ")
   (Author "// Author         : "))
   (insert cut"\n")
   (insert LastChangeTime"\n")
   (setq FILENAME (file-name-nondirectory buffer-file-name))
   (insert Name)
   (insert FILENAME"\n")
   (insert Version"\n")
   (insert Copyright"\n")
   (insert Author"张健\n")
   (insert CreatDate)
   (insert (format-time-string "%Y年%m月%e日 %p %l:%M %a"))
   (insert "\n")
   (insert Description"\n")
   (insert cut"\n")
   )
 (search-backward ":")
 (forward-char 2)
  )
